### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by alex-tee** [hotwatermorning/related-key-map#20]
Without a license, this is "All rights reserved" in many countries so other people can't use your code legally in other projects. A free license gives users the right to copy and redistribute your code. I suggest using one from this list here https://www.gnu.org/licenses/license-list.ja.html#GPLCompatibleLicenses

**Comment by hotwatermorning** [comment]
Thank you for your suggestion.

I chose MIT license for this project. Anyone can copy, modify and redistribute this project under the license.
